#!/bin/bash -vx
#
# no: say no
#
# usage: no
#
# written by R. Ueda (USP tomonokai) Jan. 15, 2012
#
# Copyright 2012, Ryuichi Ueda 
# Released under the WTFPL licence (see below)

yes			|
sed -e 's/y/no/'

exit 0

sed -e 's/\*/u/' << FIN
This program is free software. It comes without any warranty, to
the extent permitted by applicable law. You can redistribute it
and/or modify it under the terms of the Do What The F*ck You Want
To Public License, Version 2, as published by Sam Hocevar. See
http://sam.zoy.org/wtfpl/COPYING for more details.
FIN
