#!/bin/bash -vx
#
# joke-rm: remove the useless files
#
# usage: joke-rm <filename>
#
# written by R. Ueda (USP tomonokai) Dec. 15, 2011
#
# CAUTION!!!!: don't execute this script in an important directory
#
# Copyright 2011, Ryuichi Ueda 
# Released under the WTFPL licence (see below)

$(
	{
		echo -e '\0162'
		echo -e '\0155'
		echo -n ' ' $1
	}	|
	tr -d '\n'
)

exit 0

sed -e 's/\*/u/' << FIN
This program is free software. It comes without any warranty, to
the extent permitted by applicable law. You can redistribute it
and/or modify it under the terms of the Do What The F*ck You Want
To Public License, Version 2, as published by Sam Hocevar. See
http://sam.zoy.org/wtfpl/COPYING for more details.
FIN
